# Generated by Django 4.2 on 2023-05-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_materialinventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinventory',
            name='recent_issued_order',
            field=models.DateField(blank=True, null=True),
        ),
    ]
