# Generated by Django 4.2 on 2023-05-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_materialinventory_recent_issued_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
