# Generated by Django 4.2 on 2023-05-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('IP', 'In Production'), ('OP', 'Out Of Production')], default='IP', max_length=5)),
                ('lead_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_of_producing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
