# Generated by Django 4.2 on 2023-05-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_billofmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterial',
            name='id',
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='material.material'),
        ),
    ]
