# Generated by Django 4.2 on 2023-05-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_planner'),
        ('material', '0003_remove_billofmaterial_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='material.material'),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
