# Generated by Django 4.2 on 2023-05-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_billofmaterial_id_alter_billofmaterial_material_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillOfMaterial',
        ),
    ]
