# Generated by Django 4.2 on 2023-05-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_billofmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
