# Generated by Django 4.2 on 2023-05-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_alter_material_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
