# Generated by Django 4.2 on 2023-05-18 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='supplier_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='material.supplier'),
        ),
    ]
