# Generated by Django 4.2 on 2023-05-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0013_remove_material_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='supplier_new',
            new_name='supplier',
        ),
    ]
