# Generated by Django 4.2 on 2023-05-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_plan_end_date_alter_plan_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='start_date',
            new_name='start',
        ),
    ]
