# Generated by Django 4.2 on 2023-05-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_rename_end_plan_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='producable_amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='production_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
