# Generated by Django 4.2 on 2023-05-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_alter_plan_producable_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('DECLINED', 'Declined'), ('APPROVED', 'Approved'), ('PENDING', 'Pending')], default='PENDING'),
        ),
    ]
