# Generated by Django 4.2 on 2023-05-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_rename_created_machine_purchase_date_machine_price_and_more'),
        ('production', '0002_productionorder_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machine.machine'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='state',
            field=models.CharField(choices=[('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled'), ('ACTIVE', 'Active'), ('PENDING', 'Pending')], default='PENDING'),
        ),
    ]
