# Generated by Django 4.2 on 2023-05-30 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_productionorder_machine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionOrderQueue',
        ),
    ]
