# Generated by Django 4.2 on 2023-05-31 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_delete_productionorderqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('daily_produced', models.PositiveIntegerField(default=0)),
                ('produced_tracker', models.PositiveBigIntegerField(default=0)),
                ('isMyEndNear', models.BooleanField(default=False)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionorder')),
            ],
        ),
    ]
