# Generated by Django 4.2 on 2023-05-31 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_productionprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionprogress',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 12, 45, 22, 945872, tzinfo=datetime.timezone.utc)),
        ),
    ]
