# Generated by Django 4.2 on 2023-05-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_productionprogress_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionprogress',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
