# Generated by Django 4.2 on 2023-05-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('health', models.DecimalField(decimal_places=2, max_digits=3)),
                ('produced_amount', models.PositiveBigIntegerField(default=0)),
                ('last_diagnosis', models.DateField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
