# Generated by Django 4.2 on 2023-05-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='health',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
