# Generated by Django 4.2 on 2023-05-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_alter_machine_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='health',
            field=models.DecimalField(decimal_places=1, default=100.0, max_digits=4),
        ),
    ]
