# Generated by Django 4.2 on 2023-05-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_alter_machine_health'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='created',
            new_name='purchase_date',
        ),
        migrations.AddField(
            model_name='machine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
