# Generated by Django 4.2 on 2023-05-30 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_productionorderqueue'),
        ('machine', '0004_rename_created_machine_purchase_date_machine_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('daily_produced', models.PositiveIntegerField(default=0)),
                ('produced_tracker', models.PositiveBigIntegerField(default=0)),
                ('isMyEndNear', models.BooleanField(default=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionorder')),
            ],
            options={
                'unique_together': {('machine', 'production')},
            },
        ),
    ]
